apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new-image
  name: new-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-image
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new-image
    spec:

      imagePullSecrets:
        - name: ghcr-secret
       
      containers:
      
      - image: ghcr.io/anubhavbss/test-sap:ef64768cd49e19bcaef0f304f2e3b72778d9aeda
        name: test-sap
        resources: {}
status: {}
