apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new-image
  name: new-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-image
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new-image
    spec:

      imagePullSecrets:
        - name: ghcr-secret
       
      containers:
      
      - image: ghcr.io/anubhavbss/test-sap:0d82ab0789bb8a63516f921147881bf33fc35d11
        name: test-sap
        resources: {}
status: {}
